CLIP_PLAY_TIME: 10
CLIP_START_INTERVAL:
- 15
- 75
CUSTOMER_PO_TOKEN:
  po_token: ''
  visitor_data: ''
DEFAULT_COMMENT_PLACEHOLDERS: false
DOWNLOADER: bilibili
DOWNLOAD_HIGH_RES: true
FULL_LAST_CLIP: false
HTTP_PROXY: 127.0.0.1:7890
NO_BILIBILI_CREDENTIAL: false
ONLY_GENERATE_CLIPS: false
PROXY_ADDRESS: 127.0.0.1:7890
SEARCH_MAX_RESULTS: 3
SEARCH_WAIT_TIME: !!python/tuple
- 1
- 5
USE_ALL_CACHE: false
USE_AUTO_PO_TOKEN: false
USE_CUSTOM_PO_TOKEN: false
USE_OAUTH: false
USE_PROXY: false
VIDEO_BITRATE: 5000
VIDEO_RES: !!python/tuple
- 1920
- 1080
VIDEO_TRANS_ENABLE: true
VIDEO_TRANS_TIME: 1.5
